#ifndef SIMPLEFVM_FVMSOLVER_TOOLS_ENUMS_ENUMALGORITHM_H
#define SIMPLEFVM_FVMSOLVER_TOOLS_ENUMS_ENUMALGORITHM_H

namespace fvmsolver {

enum EnumAlgorithm {
	ALGORITHM_NOT_CHOSEN,
	ALGORITHM_SIMPLE,
	ALGORITHM_SIMPLER,
	ALGORITHM_PISO
};

}
#endif // SIMPLEFVM_FVMSOLVER_TOOLS_ENUMS_ENUMALGORITHM_H