#ifndef SIMPLEFVM_FVMSOLVER_TOOLS_ENUMS_ENUMADJACENTCELLTYPES_H
#define SIMPLEFVM_FVMSOLVER_TOOLS_ENUMS_ENUMADJACENTCELLTYPES_H

namespace fvmsolver {

/*
*	Cell types:
*	- ADJACENT_CELL_INTERIOR - inner adjacent cell;
*	- ADJACENT_CELL_REAL_BC  - border real adjacent cell;
*	- ADJACENT_CELL_GHOST_BC - virtual adjacent cell;
*/

enum EnumAdjacentCellTypes {
	ADJACENT_CELL_INTERIOR,
	ADJACENT_CELL_BC_REAL,
	ADJACENT_CELL_BC_GHOST
};

}
#endif // SIMPLEFVM_FVMSOLVER_TOOLS_ENUMS_ENUMADJACENTCELLTYPES_H