#ifndef SIMPLEFVM_FVMSOLVER_TOOLS_ENUMS_ENUMDIFFERENCINGSCHEME_H
#define SIMPLEFVM_FVMSOLVER_TOOLS_ENUMS_ENUMDIFFERENCINGSCHEME_H

namespace fvmsolver {

enum EnumDifferencingScheme {
	DIFF_SCHEME_NOT_CHOSEN,
	DIFF_SCHEME_CENTRAL,
	DIFF_SCHEME_UPWIND,
	DIFF_SCHEME_HYBRID
};

}
#endif // SIMPLEFVM_FVMSOLVER_TOOLS_ENUMS_ENUMDIFFERENCINGSCHEME_H

